TAG_NAME_LENGTH = 200
TAG_COLOR_LENGTH = 7
TAG_SLUG_LENGTH = 200
INGREDIENT_NAME_LENGHT = 200
INGREDIENT_MEASUREMENT_LENGHT = 200
RECIPE_NAME_LENGHT = 200

MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 2880
MIN_AMOUNT_VALUE = 1
